src/Entity/Annonce.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\DateTimeTrait;
use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: AnnonceRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Annonce
{
    use DateTimeTrait; 
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: City::class)] 
    private ?City $lieu_depart = null;

    #[ORM\ManyToOne(targetEntity: City::class)] 
    private ?City $lieu_arrivee = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'annonces')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'annonces')]
    private ?Service $service = null;

    /**
     * @var Collection<int, City>
     */
    #[ORM\ManyToMany(targetEntity: City::class, mappedBy: 'Annonce')]
    private Collection $cities;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    /**
     * @var Collection<int, Conversation>
     */
    #[ORM\OneToMany(targetEntity: Conversation::class, mappedBy: 'annonce', cascade: ['persist', 'remove'])]
    private Collection $conversations;

    public function __construct()
    {
        $this->cities = new ArrayCollection();
        $this->conversations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLieuDepart(): ?City
    {
        return $this->lieu_depart;
    }

    public function setLieuDepart(?City $lieu_depart): static
    {
        $this->lieu_depart = $lieu_depart;

        return $this;
    }

    public function getLieuArrivee(): ?City
    {
        return $this->lieu_arrivee;
    }

    public function setLieuArrivee(?City $lieu_arrivee): static
    {
        $this->lieu_arrivee = $lieu_arrivee;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->service;
    }

    public function setService(?Service $service): static
    {
        $this->service = $service;

        return $this;
    }

    /**
     * @return Collection<int, City>
     */
    public function getCities(): Collection
    {
        return $this->cities;
    }

    public function addCity(City $city): static
    {
        if (!$this->cities->contains($city)) {
            $this->cities->add($city);
            $city->addAnnonce($this);
        }

        return $this;
    }

    public function removeCity(City $city): static
    {
        if ($this->cities->removeElement($city)) {
            $city->removeAnnonce($this);
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection<int, Conversation>
     */
    public function getConversations(): Collection
    {
        return $this->conversations;
    }

    public function addConversation(Conversation $conversation): self
    {
        if (!$this->conversations->contains($conversation)) {
            $this->conversations[] = $conversation;
            $conversation->setAnnonce($this);
        }

        return $this;
    }

    public function removeConversation(Conversation $conversation): self
    {
        if ($this->conversations->removeElement($conversation)) {
            if ($conversation->getAnnonce() === $this) {
                $conversation->setAnnonce(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Entity\Traits\DateTimeTrait;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation\Uploadable;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])] // pour ne pas avoir plusieurs fois le même email en BDD
#[UniqueEntity(fields: ['siren'], message: 'Informations déjà existantes')] // assure que çe champ reste unique en bdd
#[ORM\HasLifecycleCallbacks] 
#[Uploadable] // indique que cette entité est "uploadable"
class User implements UserInterface, PasswordAuthenticatedUserInterface 
{
    use DateTimeTrait; 

    #[ORM\Id]
    #[ORM\GeneratedValue] // génère automatiquement l'id en bdd
    #[ORM\Column] // correspond à une colonne en bdd
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(max: 255)] 
    #[Assert\NotBlank()] // empêche la soumission du form vide
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(max: 255)]
    #[Assert\NotBlank()] // empêche la soumission du form vide
    private ?string $lastName = null;

    #[ORM\Column(length: 180)] // colonne de max 180 caractères
    #[Assert\Length(max: 180)] // chaine 180 caractères max
    #[Assert\NotBlank(message: 'L\'adresse email ne peut pas être vide.')] 
    #[Assert\Email(message: 'Email invalide.')] // oblige l'utilisateur à mettre un email valide
    private ?string $email = null;

     /**
     * @var list<string> 
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string 
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 9)]
    #[Assert\NotBlank(message: 'Le numéro de Siren ne peut pas être vide.')]
    #[Assert\Regex(
        pattern: '/^\d{9}$/',
        message: 'Le numéro de Siren doit être composé de 9 chiffres.'
    )]
    private ?string $siren = null;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])] // pareil qu'en haut
    private ?Payment $payment = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToOne(targetEntity:UserInfos::class, inversedBy: 'user', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(name: "user_infos_id", referencedColumnName: "id")]
    private ?UserInfos $UserInfos = null;

    /**
     * @var Collection<int, Annonce>
     */
    #[ORM\OneToMany(targetEntity: Annonce::class, mappedBy: 'user', cascade: ['remove'])]
    private Collection $annonces;

    /**
     * @var Collection<int, Conversation>
     */
    #[ORM\OneToMany(targetEntity: Conversation::class, mappedBy: 'creator')]
    private Collection $conversations;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'sender')]
    private Collection $messages;

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
        $this->conversations = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // Garantis que chaque utilisateur a au moins un rôle
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getSiren(): ?string
    {
        return $this->siren;
    }

    public function setSiren(string $siren): static
    {
        $this->siren = $siren;

        return $this;
    }

    public function getPayment(): ?Payment
    {
        return $this->payment;
    }

    public function setPayment(?Payment $payment): static
    {
        $this->payment = $payment;

        // ??
        $newUser = $payment === null ? null : $this;
        if ($newUser !== $payment->getUser()) {
            $payment->setUser($newUser);
        }

        return $this;
    }

    public function getUserInfos(): ?UserInfos
    {
        return $this->UserInfos;
    }

    public function setUserInfos(?UserInfos $UserInfos): static
    {
        $this->UserInfos = $UserInfos;

        return $this;
    }

    /**
     * @return Collection<int, Annonce>
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): static
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces->add($annonce);
            $annonce->setUser($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): static
    {
        if ($this->annonces->removeElement($annonce)) {
            // set the owning side to null (unless already changed)
            if ($annonce->getUser() === $this) {
                $annonce->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Conversation>
     */
    public function getConversations(): Collection
    {
        return $this->conversations;
    }

    public function addConversation(Conversation $conversation): static
    {
        if (!$this->conversations->contains($conversation)) {
            $this->conversations->add($conversation);
            $conversation->setCreator($this);
        }

        return $this;
    }

    public function removeConversation(Conversation $conversation): static
    {
        if ($this->conversations->removeElement($conversation)) {
            // set the owning side to null (unless already changed)
            if ($conversation->getCreator() === $this) {
                $conversation->setCreator(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setSender($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getSender() === $this) {
                $message->setSender(null);
            }
        }

        return $this;
    }
}

src/Controller/Admin/AnnonceController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Annonce;
use App\Form\AnnonceType;
use App\Repository\AnnonceRepository;
use App\Repository\UserInfosRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/admin/annonce', name: 'admin.annonce', methods: ['GET'])]
class AnnonceController extends AbstractController
{
    #[Route('/', name: '.index')]
    public function index(AnnonceRepository $annonceRepo): Response
    {
        return $this->render('Admin/Annonce/index.html.twig', [
            'annonces' => $annonceRepo->findAllOrderedByCreatedAt(),
        ]);
    }

    #[Route('/create', name: '.create', methods: ['GET', 'POST'])]
    public function create(Request $request, EntityManagerInterface $em): Response 
    {
        $annonce = new Annonce();

        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request); //  traite la requête et met à jour l'entité avec les données soumises du formulaire

        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($annonce);
            $em->flush();

            $this->addFlash('success', 'Annonce créer avec succès.');

            return $this->redirectToRoute('admin.annonce.index');
        }

        return $this->render('Admin/Annonce/create.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/{id}/edit', name: '.edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Annonce $annonce, EntityManagerInterface $em): Response 
    {
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            $this->addFlash('success', 'Annonce modifié avec succès.');
            return $this->redirectToRoute('admin.annonce.index');
        }

        return $this->render('Admin/Annonce/edit.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: '.delete', methods: ['POST'])]
    public function delete(Annonce $annonce, Request $request, EntityManagerInterface $em): Response 
    {
        if ($this->isCsrfTokenValid('delete' . $annonce->getId(), $request->request->get('_token'))) {
            $em->remove($annonce);
            $em->flush();

            $this->addFlash('success', 'Annonce supprimé avec succès.');
        } else {
            $this->addFlash('error', 'Erreur lors de la suppression de l\'annonce.');
        }

        return $this->redirectToRoute('admin.annonce.index');
    }
}

templates/Backend/Annonce/_form.html.twig
<div class="center-form">
    <div class="form-user">
        <div class="img-form" id="anim-img-create-annonce">
            <img src="{{ asset('images/logo-png.png') }}" alt="Image du logo de l'entreprise.">
        </div>
        <div>
            <h1 id="anim-title-create-annonce">Annonce</h1>
            <div class="form-label-input margin-top-20">
                <div id="anim-form-create-annonce">
                {{ form_start(form) }}
                <div class="form-group">
                    <label for="">Titre de l'annonce <span class="little-star">*</span></label>
                    {{ form_widget(form.title) }}
                </div>
                <div class="form-group">
                    <label for="date">Date <span class="little-star">*</span></label>
                    {{ form_widget(form.date) }}
                </div>
                <div class="form-group">
                    <label for="">Lieu de départ <span class="little-star">*</span></label>
                    {{ form_widget(form.lieu_depart) }}
                </div>
                <div class="form-group">
                    <label for="">Lieu d'arrivée <span class="little-star">*</span></label>
                    {{ form_widget(form.lieu_arrivee) }}
                </div>
                <div class="form-group">
                    <label for="">Description <span class="little-star">*</span></label>
                    {{ form_widget(form.description) }}
                </div>
                <div class="form-group">
                    <label for="">Quels service proposez-vous <span class="little-star">*</span></label>
                    {{ form_widget(form.service) }}
                </div>
                </div>
                <div class="margin-top-20 margin-bottom-50" id="anim-btn-form-annonce">
                    <button type="submit" class="btn-new">Mettre en ligne</button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
</div>
    

templates/Backend/Annonce/_formSearch.html.twig
<section class="margin-top-30">
    <p class="margin-bottom-5" id="anim-title-annonce-1">Rechercher une annonce</p>
    <div class="menu-list-infos">
     <button class="menu-button-infos annonce-button-infos" id="anim-form-search">
            <div class="d-flex align-item-center gap-8">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" /></svg>                                                          
                Recherche                        
            </div>
            <span class="arrow-info search-arrow">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5"/>
                </svg>
            </span>
        </button>
        <div class="annonce-menu-search first-annonce-search">
            <div class="form-center-search"> 
                <div class="form-search"> 
                    <div>
                        <div class="form-label-input margin-top-20">
                        {{ form_start(form) }}
                            <div class="form-group">
                                <label for="date">Lieu de départ <span class="little-star">*</span></label>
                                {{ form_widget(form.lieu_depart) }}
                            </div>
                            <div class="form-group">
                                <label for="date">Lieu d'arrivée <span class="little-star">*</span></label>
                                {{ form_widget(form.lieu_arrivee) }}
                            </div>
                            <div class="form-group">
                                <label for="date">Date <span class="little-star">*</span></label>
                                {{ form_widget(form.date) }}
                            </div>
                            <div class="form-group">
                                <label for="">Quel service cherchez-vous ? <span class="little-star">*</span></label>
                                {{ form_widget(form.service) }}
                            </div>
                            <div class="form-group margin-top-20 margin-bottom-50">
                                {{ form_widget(form.search) }}
                            </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</section>

templates/Backend/Annonce/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'une annonce{% endblock %}

{% block body %}
    {% include "Backend/Annonce/_form.html.twig" %}
{% endblock %}

templates/Backend/Annonce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonces{% endblock %}

{% block body %}
    {% include "Layout/nav.html.twig" %}

    <div class="annonce-full">

        <div class="header-title">
            <div class="header-title-widget d-flex" id="anim-header-annonce">
                <img src="{{ asset('images/logo-png.png') }}" alt="Image du logo de l'entreprise.">
                <p>Accueil</p>
            </div>
        </div>

        <div class="annonce-center">

            {% include "Backend/Annonce/_formSearch.html.twig" %}
    
            <div class="margin-top-30 padding-bottom-150">
                <p class="margin-bottom-5" id="anim-title-annonce-2">Chauffeurs disponible</p>
                {% if annonces|length > 0 %}
                    {% for annonce in annonces %}
                    <div class="menu-list-infos" id="anim-list-annonces">
                        <button class="menu-button-infos annonce-second-button-infos">
                            <div class="d-flex align-item-center gap-8">
                                <img src="{{ asset('images/photo/' ~ annonce.user.userInfos.photoName) }}" alt="Photo du chauffeur." class="img-annonce-list">
                                {{ annonce.user.firstName }} {{ annonce.user.lastName }}
                            </div>
                            <span class="arrow-info annonce-arrow">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5"/>
                                </svg>
                            </span>
                        </button>
                        <div class="annonce-menu-search first-annonce-list">
                            <div class="d-flex gap-8 padding-10">
                                <span class="bold">Titre :</span>
                                <p>{{ annonce.title }}</p>
                            </div>
                            <div class="d-flex gap-8 padding-10">
                                <span class="bold">Description :</span>
                                <p>{{ annonce.description }}</p>
                            </div>
                            <div class="d-flex gap-8 padding-10">
                                <span class="bold">Disponible le :</span>
                                <p>{{ annonce.date|date('d/m/Y') }}</p>
                            </div>
                            <div class="d-flex gap-8 padding-10">
                                <span class="bold">Service :</span>
                                <p>{{ annonce.service.name }}</p>
                            </div>
                            <div class="d-flex gap-8 padding-10">
                                <span class="bold">Lieu de départ :</span>
                                <p>{{ annonce.lieuDepart }}</p>
                            </div>
                            <div class="d-flex gap-8 padding-10">
                                <span class="bold">Lieu d'arrivée :</span>
                                <p>{{ annonce.lieuArrivee }}</p>
                            </div>
                            <div class="d-flex gap-8 padding-10">
                                <a href="{{ path('app.conversation.new', {'id': annonce.id}) }}">Contacter</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                {% else %}
                    <div class="margin-top-50">
                        <p>Aucune annonce en ligne.</p>
                    </div>
                {% endif %}
                
            </div>
        </div>
    </div>
{% endblock %}